variables:
  DOCKER_DRIVER: overlay2 # use faster volume driver
  DOCKER_IMAGE: registry.gitlab.com/publicmarket/storefront

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

stages:
  - build
  - test

build:
  stage: build
  tags:
    - build
  image: docker:latest
  script:
    - docker build -f ./config/deploy/Dockerfile -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
    - docker system prune -f

rspec:
  image: $DOCKER_IMAGE:latest
  stage: test
  services:
    - postgres:10.1-alpine
    - redis:alpine
    - elasticsearch:latest
  cache:
    paths:
      - vendor/bundle
      - apt-cache/
  variables:
    POSTGRES_DB: bookstore_test
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
    REDIS_HOST: redis
    ELASTICSEARCH_URL: http://elasticsearch:9200
    RAILS_ENV: test
  before_script:
    - curl -sS -L https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -qq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -yqq google-chrome-stable
    - bundle check || bundle install --deployment --jobs 4 --without development staging production
    - bundle exec rake db:schema:load
  script:
    - bundle exec rspec
