AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Include:
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /_decorator.rb/
    - 'app/swagger/**/*'
    - 'config/**/*'
    - 'db/**/*'

# DISABLED

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/Output:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
