AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/initializers/simple_form_bootstrap.rb'

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
    - api_db

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: compact

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - !ruby/regexp /_decorator.rb/
    - 'app/swagger/**/*'
    - 'config/**/*'
    - 'db/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/mailers/**/*'

# DISABLED

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/Output:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
