AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Include:
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
    - '**/Brewfile'
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'

Rails:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: compact

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'db/**/*'

# DISABLED

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
