AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Include:
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Guardfile'
    - '**/Brewfile'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: compact

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 150
