default: &default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: storefront_development
  pool: <%= ENV['WEB_THREADS'] || 25 %>
  username: postgres
  password: postgres

test:
  <<: *default
  database: storefront_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: postgres
  password: postgres

staging:
  <<: *default
  database: storefront_staging
  pool: <%= ENV['WEB_THREADS'] || 25 %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: storefront_production
  pool: <%= ENV['WEB_THREADS'] || 25 %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

api_db:
  adapter: sqlite3
  database: db/storefront_api.sqlite3
