default: &default
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bookstore_development
  pool: <%= ENV['WEB_THREADS'] || 10 %>
  username: postgres
  password: postgres

test:
  <<: *default
  database: bookstore_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: postgres
  password: postgres

staging:
  <<: *default
  database: bookstore_staging
  pool: <%= ENV['WEB_THREADS'] || 10 %>
  username: postgres
  password: <%= Settings.db_password %>
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: bookstore_production
  pool: <%= ENV['WEB_THREADS'] || 10 %>
  password: <%= Settings.db_password %>
  host: <%= ENV['DB_HOST'] %>
