default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *default
  database: bookstore_development
  pool: <%= ENV['WEB_THREADS'] || 10 %>

test:
  <<: *default
  database: bookstore_test<%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *default
  database: bookstore_staging
  pool: <%= ENV['WEB_THREADS'] || 10 %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: bookstore_production
  pool: <%= ENV['WEB_THREADS'] || 10 %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
