---
:concurrency: 10
:queues:
  - default
  - paperclip
  - mailers
  - upload
  - searchkick
  - recalculation
  - orders
  - payments
:schedule:
  capture_payments:
    cron: '*/30 * * * *' # Runs at every 30th minute
    class: CapturePayments
    queue: payments
    description: 'Capture pending payments'
  upload_order_report:
    cron: '0 0 * * * *' # Runs every hour
    class: UploadOrderReport
    queue: orders
    args: ['Second Seller', 'test_ftp']
    description: 'Upload order report'
  process_order_updates:
    cron: '*/10 * * * *' # Runs at every 10th minute
    class: ProcessOrderUpdates
    queue: orders
    args: ['Second Seller', 'test_ftp']
    description: 'Process order updates'
