---
:concurrency: 10
:queues:
  - payments
  - orders
  - files
  - default
  - searchkick
  - paperclip
  - mailers
  - upload
  - recalculation
:schedule:
  capture_payments:
    cron: '*/30 * * * *' # Runs at every 30th minute
    class: CapturePayments
    queue: payments
    description: 'Capture pending payments'
  upload_order_report:
    cron: '0 0 * * * *' # Runs every hour
    class: UploadOrderReport
    queue: orders
    args: ['bwb', 'bwb_ftp']
    description: 'Upload order report'
  process_order_updates:
    cron: '*/10 * * * *' # Runs at every 10th minute
    class: ProcessOrderUpdates
    queue: orders
    args: ['bwb', 'bwb_ftp']
    description: 'Process order updates'
  fetch_bwb_inventory:
    cron: '0 0 * * * *' # Runs every hour
    class: PublicMarket::Workers::FTP::FetchInventoryFiles
    queue: files
    args: ['bwb', 'bwb_ftp']
    description: 'Fetch bwb inventory'
