require: rubocop-rspec

inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 6

RSpec/ExampleLength:
  Max: 6

RSpec/AnyInstance:
  Enabled: false

RSpec/FilePath:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
