apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"