apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: app-pod-preset
spec:
  selector:
    matchLabels:
      type: rails
  env:
    - name: RAILS_ENV
      value: staging
    - name: RACK_ENV
      value: staging
    - name: DB_HOST
      value: postgres-service
  volumeMounts:
    - mountPath: '/bundle'
      name: storage
      subPath: bundles
    - mountPath: '/app/public'
      name: storage
      subPath: assets
    - mountPath: '/app/logs'
      name: storage
      subPath: logs
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: pv-claim