version: '3.2'

services:
  app:
    build:
      context: ../../.
      dockerfile: ./config/deploy/Dockerfile
    command: bundle exec puma
    volumes:
      - bundle_cache:/bundle
      - app_public:/app/public
    restart: always

  sidekiq:
    image: bookstore_app
    command: bundle exec sidekiq
    volumes:
      - bundle_cache:/bundle
      - app_public:/app/public
      - sidekiq_logs:/app/log
    restart: always

volumes:
  bundle_cache:
  app_public:
  sidekiq_logs:
