version: '3.2'

services:
  app:
    ports:
      - '80:3000'
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - RACK_ENV=staging
      - RAILS_ENV=staging

  postgres:
    image: postgres:10.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
