version: '3.2'

services:
  app:
    ports:
      - '80:3000'
    depends_on:
      - postgres
      - redis
    environment: &app_env
      DB_HOST: postgres
      RACK_ENV: staging
      RAILS_ENV: staging
      REDIS_HOST: redis
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - tmp_uploads:/app/tmp/uploads

  sidekiq:
    depends_on:
      - postgres
      - redis
    environment:
      <<: *app_env
    volumes:
      - tmp_uploads:/app/tmp/uploads

  postgres:
    image: postgres:10.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres:
  tmp_uploads:
  esdata:
