version: '3.2'

services:
  app:
    ports:
      - '80:3000'
    depends_on:
      - postgres
      - redis
    environment: &app_env
      DB_HOST: postgres
      RACK_ENV: staging
      RAILS_ENV: staging
      REDIS_HOST: redis
    restart: always

  sidekiq:
    depends_on:
      - postgres
      - redis
    environment:
      <<: *app_env
    restart: always

  postgres:
    image: postgres:10.1-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres:
